# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  server:
    command: npx nodemon --legacy-watch --verbose index.js
    build:
      context: .
    environment:
      NODE_ENV: development
      PORT: 3003
      DB_HOST: db  
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: alo_draft_app
      DB_PORT: 3306
      JWT_SECRET: your_secure_jwt_secret_key
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app  # Maps your local code to the container
      - /usr/src/app/node_modules  # Preserves the container's node_modules
    # If you have nodemon installed in your project, you can use this for auto-reloading
    # command: npm run dev  # Uncomment if you have a dev script that uses nodemon
  
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Empty password as in your env
      MYSQL_DATABASE: alo_draft_app
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty root password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Add phpMyAdmin for easier database management
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=""
    depends_on:
      - db

volumes:
  db-data:  # This volume persists your database data